# Generated by Django 4.0.6 on 2022-07-13 20:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150, null=True)),
                ('author', models.CharField(max_length=25, null=True)),
                ('price', models.IntegerField(null=True)),
                ('description', models.CharField(blank=True, max_length=3000, null=True)),
                ('address', models.CharField(max_length=150, null=True)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
